name: Daily Data Update

on:
  schedule:
    # 매일 한국 시간 오전 9시 (UTC 0시)
    - cron: '0 0 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build database
      env:
        CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        CONFLUENCE_EMAIL: ${{ secrets.CONFLUENCE_EMAIL }}
        CONFLUENCE_DOMAIN: ${{ secrets.CONFLUENCE_DOMAIN }}
        MOMGLEEDU_CONFLUENCE_DOMAIN: ${{ secrets.MOMGLEEDU_CONFLUENCE_DOMAIN }}
      run: |
        mkdir -p public
        node scripts/build-db.js
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add public/requests.db
        git diff --staged --quiet || git commit -m "Update database $(date +'%Y-%m-%d')"
        git push || true
    
    - name: Trigger Vercel deployment
      run: |
        curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}